In [4]:
import numpy as np
def iris_type(s):
    it={b'Iris-setosa':0,b'Iris-versicolor':1,b'Iris-virginica':2}
    return it[s]
path = '/Users/tequila2411/Desktop/Iris.data'
data = np.loadtxt(path,dtype=float,delimiter=',',converters={4:iris_type})

In [9]:
from sklearn import svm
from sklearn.model_selection import train_test_split
x,y = np.split(data,(4,),axis=1)
x = x[:,:2]
x_train,x_test,y_train,y_test =train_test_split(x,y,random_state=1,test_size=0.6)
print("x_train:",x_train)
print("x_test:",x_test)
print("y_train:",y_train)
print("y_test:",y_test)

x_train: [[5.8 2.7]
 [4.9 3.1]
 [7.4 2.8]
 [6.2 2.9]
 [7.6 3. ]
 [6.7 3. ]
 [6.3 2.3]
 [6.2 3.4]
 [7.2 3.6]
 [5.6 2.9]
 [5.7 4.4]
 [5.8 2.7]
 [4.5 2.3]
 [5.5 2.4]
 [6.9 3.1]
 [5.  3.4]
 [6.8 2.8]
 [5.  3.5]
 [4.8 3.4]
 [6.3 3.4]
 [5.6 2.8]
 [6.8 3.2]
 [5.  3.3]
 [5.1 3.7]
 [5.9 3.2]
 [4.6 3.1]
 [5.8 2.7]
 [4.8 3.1]
 [6.5 3. ]
 [4.9 2.5]
 [4.6 3.2]
 [6.4 3.2]
 [4.3 3. ]
 [5.6 3. ]
 [4.4 2.9]
 [5.5 2.4]
 [5.  2. ]
 [5.1 3.5]
 [4.9 3. ]
 [4.9 2.4]
 [4.6 3.6]
 [5.9 3. ]
 [6.1 2.9]
 [5.  3.4]
 [6.7 3.1]
 [5.7 2.9]
 [6.2 2.2]
 [7.  3.2]
 [5.8 2.7]
 [5.4 3.4]
 [5.  3. ]
 [6.1 2.6]
 [6.1 2.8]
 [7.2 3. ]
 [5.7 2.6]
 [6.3 2.8]
 [6.4 3.1]
 [6.3 2.5]
 [6.7 3.1]
 [4.9 3.1]]
x_test: [[5.8 4. ]
 [5.1 2.5]
 [6.6 3. ]
 [5.4 3.9]
 [7.9 3.8]
 [6.3 3.3]
 [6.9 3.1]
 [5.1 3.8]
 [4.7 3.2]
 [6.9 3.2]
 [5.6 2.7]
 [5.4 3.9]
 [7.1 3. ]
 [6.4 3.2]
 [6.  2.9]
 [4.4 3.2]
 [5.8 2.6]
 [5.6 3. ]
 [5.4 3.4]
 [5.  3.2]
 [5.5 2.6]
 [5.4 3. ]
 [6.7 3. ]
 [5.  3.5]
 [7.2 3.2]
 [5.7 2.8]
 [5.5 4.2]
 [5.1 3.8]
 [6.1 2.8]
 [6

In [29]:
from sklearn import svm
clf = svm.SVC(C =0.8,kernel="rbf",gamma=20, decision_function_shape='ovr')
clf.fit(x_train,y_train.ravel())
print(clf.score(x_train,y_train))
y_hat = clf.predict(x_train)
print(y_hat)
print(clf.score(x_test,y_test))
y_hat = clf.predict(x_test)
print(y_hat)
print("decision_function:",clf.decision_function(x_train))
print("prediction:",clf.predict(x_train))

0.8666666666666667
[1. 0. 2. 1. 2. 2. 1. 2. 2. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 2. 1. 1. 0. 0.
 1. 0. 1. 0. 2. 1. 0. 2. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 2. 1. 1. 1.
 1. 0. 0. 1. 1. 2. 1. 1. 2. 1. 2. 0.]
0.6111111111111112
[1. 1. 2. 1. 1. 2. 1. 0. 0. 1. 1. 1. 1. 2. 1. 0. 1. 1. 0. 0. 1. 1. 2. 0.
 1. 1. 1. 0. 1. 1. 1. 2. 1. 2. 1. 0. 1. 0. 2. 1. 1. 0. 1. 1. 2. 1. 1. 0.
 0. 1. 0. 0. 1. 1. 2. 2. 1. 1. 2. 1. 0. 1. 1. 0. 0. 2. 0. 1. 2. 2. 1. 2.
 1. 0. 1. 2. 2. 1. 2. 1. 0. 0. 1. 2. 0. 1. 1. 1. 0. 0.]
decision_function: [[-0.45750105  2.41012152  1.04737954]
 [ 2.5         0.80516072 -0.30516072]
 [-0.27218664  0.84236313  2.42982352]
 [-0.40403966  2.40438424  0.99965542]
 [-0.27182091  0.8709452   2.40087571]
 [-0.460444    1.1245457   2.3358983 ]
 [-0.27328652  2.45759739  0.81568912]
 [-0.28426086  0.83902516  2.44523569]
 [-0.26166428  0.92135325  2.34031103]
 [-0.40929703  2.43812913  0.97116791]
 [ 2.29079833  0.91523981 -0.20603814]
 [-0.45750105  2.41012152  1.04737954]
 [ 2.28131515  0

In [33]:
x1_min, x1_max = x[:, 0].min(), x[:, 0].max()  # 第0列的范围
x2_min, x2_max = x[:, 1].min(), x[:, 1].max()  # 第1列的范围
x1, x2 = np.mgrid[x1_min:x1_max:200j, x2_min:x2_max:200j]  # 生成网格采样点
print("x1:\n",x1,"\n","x2:\n",x2)
grid_test = np.stack((x1.flat, x2.flat), axis=1)  # 测试点
print("grid_test:\n",grid_test)

x1:
 [[4.3        4.3        4.3        ... 4.3        4.3        4.3       ]
 [4.31809045 4.31809045 4.31809045 ... 4.31809045 4.31809045 4.31809045]
 [4.3361809  4.3361809  4.3361809  ... 4.3361809  4.3361809  4.3361809 ]
 ...
 [7.8638191  7.8638191  7.8638191  ... 7.8638191  7.8638191  7.8638191 ]
 [7.88190955 7.88190955 7.88190955 ... 7.88190955 7.88190955 7.88190955]
 [7.9        7.9        7.9        ... 7.9        7.9        7.9       ]] 
 x2:
 [[2.        2.0120603 2.0241206 ... 4.3758794 4.3879397 4.4      ]
 [2.        2.0120603 2.0241206 ... 4.3758794 4.3879397 4.4      ]
 [2.        2.0120603 2.0241206 ... 4.3758794 4.3879397 4.4      ]
 ...
 [2.        2.0120603 2.0241206 ... 4.3758794 4.3879397 4.4      ]
 [2.        2.0120603 2.0241206 ... 4.3758794 4.3879397 4.4      ]
 [2.        2.0120603 2.0241206 ... 4.3758794 4.3879397 4.4      ]]
grid_test:
 [[4.3       2.       ]
 [4.3       2.0120603]
 [4.3       2.0241206]
 ...
 [7.9       4.3758794]
 [7.9       4.3879397]
 [7.

In [35]:
import matplotlib.pyplot as plt
import matplotlib as mpl 
from matplotlib import colors 
mpl.rcParams['font.sans-serif'] = [u'SimHei']
mpl.rcParams['axes.unicode_minus'] = False

cm_light = mpl.colors.ListedColormap(['#A0FFA0', '#FFA0A0', '#A0A0FF'])
cm_dark = mpl.colors.ListedColormap(['g', 'r', 'b'])

# print 'grid_test = \n', grid_test
grid_hat = clf.predict(grid_test)  # 预测分类值
grid_hat = grid_hat.reshape(x1.shape)  # 使之与输入的形状相同

alpha = 0.5
plt.pcolormesh(x1, x2, grid_hat, cmap=cm_light)  # 预测值的显示
# plt.plot(x[:, 0], x[:, 1], 'o', alpha=alpha, color='blue', markeredgecolor='k')
plt.scatter(x[:,0],x[:,1],s=50,cmap=cm_dark,edgecolors='k',alpha=alpha)
plt.scatter(x_test[:, 0], x_test[:, 1], s=120, facecolors='none', zorder=10)  # 圈中测试集样本
plt.xlabel(u'花萼长度', fontsize=13)
plt.ylabel(u'花萼宽度', fontsize=13)
plt.xlim(x1_min, x1_max)
plt.ylim(x2_min, x2_max)
plt.title(u'鸢尾花SVM二特征分类', fontsize=15)
# plt.grid()
plt.show()

/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py:1328: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
